/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NFloatButton: typeof import('naive-ui')['NFloatButton']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const NAvatar: typeof import('naive-ui')['NAvatar']
  const NButton: typeof import('naive-ui')['NButton']
  const NCard: typeof import('naive-ui')['NCard']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NFloatButton: typeof import('naive-ui')['NFloatButton']
  const NForm: typeof import('naive-ui')['NForm']
  const NFormItem: typeof import('naive-ui')['NFormItem']
  const NIcon: typeof import('naive-ui')['NIcon']
  const NImage: typeof import('naive-ui')['NImage']
  const NInput: typeof import('naive-ui')['NInput']
  const NInputNumber: typeof import('naive-ui')['NInputNumber']
  const NLayout: typeof import('naive-ui')['NLayout']
  const NLayoutContent: typeof import('naive-ui')['NLayoutContent']
  const NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
  const NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
  const NLayoutSider: typeof import('naive-ui')['NLayoutSider']
  const NMenu: typeof import('naive-ui')['NMenu']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}